name: Build and Generate SLSA Provenance
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: slsa-framework/github-actions/provenance@main
      with:
        entrypoint: dotnet publish --self-contained -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true
